PROC SQL;
	SELECT DISTINCT T1.PATIENT_ID, T1.PROFESSION, T2.PROFESSION, T1.VISIT_DATE as date format=datetime20., T1.IMP_AGE
	FROM WORK.PREABT T1 LEFT JOIN WORK.PREABT T2
		ON T1.PATIENT_ID = T2.PATIENT_ID
	WHERE 
		T1.PROFESSION <> T2.PROFESSION;
RUN;

PROC SQL;
	SELECT DISTINCT T1.PATIENT_ID, T1.IMP_AGE, T2.IMP_AGE
	FROM WORK.PREABT T1 LEFT JOIN WORK.PREABT T2
		ON T1.PATIENT_ID = T2.PATIENT_ID
	WHERE 
		T1.IMP_AGE <> T2.IMP_AGE;
RUN;

PROC SQL;
	SELECT DISTINCT T1.PATIENT_ID, T1.GENDER, T1.VISIT_DATE as date format=datetime20.
	FROM WORK.PREABT T1 LEFT JOIN WORK.PREABT T2
		ON T1.PATIENT_ID = T2.PATIENT_ID
	WHERE 
		T1.GENDER <> T2.GENDER;
RUN;

PROC SQL;
	SELECT DISTINCT T1.PATIENT_ID, T1.IMP_AGE
	FROM WORK.PREABT T1 LEFT JOIN WORK.PREABT T2
		ON T1.PATIENT_ID = T2.PATIENT_ID
	WHERE 
		T1.IMP_INSURANCE_PROVIDER <> T2.IMP_INSURANCE_PROVIDER;
RUN;

PROC SQL;
	SELECT DISTINCT T1.PATIENT_ID, T1.FAMILY_HISTORY, T2.FAMILY_HISTORY
	FROM WORK.PREABT T1 LEFT JOIN WORK.PREABT T2
		ON T1.PATIENT_ID = T2.PATIENT_ID
	WHERE 
		T1.FAMILY_HISTORY <> T2.FAMILY_HISTORY;
RUN;

PROC SQL;
	SELECT DISTINCT T1.PATIENT_ID, T1.MARITAL_STATUS, T2.MARITAL_STATUS, T1.VISIT_DATE as date format=datetime20.
	FROM WORK.PREABT T1 LEFT JOIN WORK.PREABT T2
		ON T1.PATIENT_ID = T2.PATIENT_ID
	WHERE 
		T1.MARITAL_STATUS <> T2.MARITAL_STATUS;
RUN;

PROC SQL;
	SELECT DISTINCT T1.PATIENT_ID, T1.CITY_OF_RESIDENCE, T2.CITY_OF_RESIDENCE
	FROM WORK.PREABT T1 LEFT JOIN WORK.PREABT T2
		ON T1.PATIENT_ID = T2.PATIENT_ID
	WHERE 
		T1.CITY_OF_RESIDENCE <> T2.CITY_OF_RESIDENCE;
RUN;

PROC SQL;
	SELECT DISTINCT T1.PATIENT_ID
	FROM WORK.PREABT T1 LEFT JOIN WORK.PREABT T2
		ON T1.PATIENT_ID = T2.PATIENT_ID
	WHERE 
		T1.IMP_APPROXIMATE_ANNUAL_INCOME <> T2.IMP_APPROXIMATE_ANNUAL_INCOME;
RUN;

PROC SQL;
	SELECT PATIENT_ID, Satisfaction_Level
	FROM WORK.PREABT
	WHERE
		SATISFACTION_LEVEL > 5 OR SATISFACTION_LEVEL < 0;
RUN;


PROC SQL;
	SELECT IMP_AGE, PROFESSION
	FROM WORK.PREABT
	WHERE IMP_AGE < 17 AND NOT(Profession='Student');
RUN;


PROC SQL;
	SELECT DISTINCT T1.PATIENT_ID, T1.PROFESSION, T1.IMP_APPROXIMATE_ANNUAL_INCOME
	FROM WORK.PREABT T1 LEFT JOIN WORK.PREABT T2
		ON T1.PATIENT_ID = T2.PATIENT_ID
	WHERE 
		NOT(T1.PROFESSION='Student' or T1.PROFESSION='Retired') AND T1.IMP_APPROXIMATE_ANNUAL_INCOME=0;
RUN;


PROC SQL;
	SELECT DISTINCT T1.PATIENT_ID
	FROM WORK.PREABT T1 LEFT JOIN WORK.PREABT T2
		ON T1.PATIENT_ID = T2.PATIENT_ID
	WHERE 
		T1.IMP_APPROXIMATE_ANNUAL_INCOME < 0 or
		T1.IMP_AGE < 0;
RUN;
